assistants:
  standard:
    id: "asst_jeHiEoUgYxd2oOjxZyqIP4YR"
    title: "æ ‡å‡†ç‰ˆAPI Chatbot"
    icon: "ğŸ¤–"
    description: "ğŸš€ A chatbot powered by å‘ç¥¨äº‘"
    llm_txt_url: "https://open-standard.piaozone.com/llms.txt"
  
  ultimate:
    id: "asst_TTZaGdtxROyACaoNCCSOigSw"
    title: "æ——èˆ°ç‰ˆAPI Chatbot"
    icon: "ğŸ¤–"
    description: "ğŸš€ A chatbot powered by å‘ç¥¨äº‘"
    llm_txt_url: "https://open.piaozone.com/llms.txt"

  ai:
    id: "asst_e8YKjgA3MqAb6HfPUPtglBrI"
    title: "æ™ºèƒ½ç‰¹æ€§API Chatbot"
    icon: "ğŸ¤–"
    description: "ğŸš€ A chatbot powered by å‘ç¥¨äº‘"
    llm_txt_url: "https://open-ai.piaozone.com/llms.txt" 
  
  test:
    id: "asst_p4dOO2s1LElJMoU7usSj9qar"
    title: "API Chatbot"
    icon: "ğŸ¤–"
    description: "ğŸš€ A chatbot powered by å‘ç¥¨äº‘"
    llm_txt_url: "https://piaozone-open.apifox.cn/llms.txt"   